### ISSUE TITLE
Feature request: Making cell selection in multiplexed pixel clustering deterministic

### ISSUE THREAD

**Issue by Kelvin579** [Apricot-Therapeutics/APx_fractal_task_collection#2]
Is it possible to make the cell selection within the given coordinates in the task multiplexed pixel clustering deterministic by adding a random seed option? I.e. so that you can run MCUs with different parameters/stains for the same single cells and compare them.

**Comment by adrtsc** [comment]
I added this option along with the update to Fractal 2.0 in the APx Fractal Task Collection v0.3.0.
