### ISSUE TITLE
Add `defusedxml` dependency

### ISSUE THREAD

**Issue by tcompa** [Apricot-Therapeutics/APx_fractal_task_collection#7]
APx uses `defusedxml` but this dependency is not listed in `pyproject.toml`.
fractal-tasks-core dropped this dependency as of v1.3.0 (https://github.com/fractal-analytics-platform/fractal-tasks-core/blob/main/CHANGELOG.md#130), therefore it should be included explicitly in APx.

**Comment by adrtsc** [comment]
Included it as a dependency. Thanks for the heads up!
